project:
  type: website
  output-dir: docs

website:
  title: "Peter Bruun-Rasmussen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - cv.qmd
      - mymusic.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full