project:
  type: website
  output-dir: docs

website:
  title: "Peter Bruun-Rasmussen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - publications.qmd
      - cv.qmd
      - mymusic.qmd
      - poems.qmd
    tools:
    - icon: linkedin 
      text: LinkedIn
      href: https://dk.linkedin.com/in/peter-bruun-rasmussen
    - icon: github
      text: GitHub
      href: https://github.com/peterbruun
    - icon: twitter
      text: Twitter
      href: https://x.com/PeterBruunRasm1
    - icon: google 
      text: Google Scholar
      href: https://scholar.google.com/citations?user=QepyB-wAAAAJ&hl=en&oi=ao
    - icon: mailbox
      text: Email
      href: mailto:peter@bruun-rasmussen.info

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full