---
layout: poems
title: Poems
---
Once in a while I like to entertain myself with writing poems. 
Most are in Danish, here are a few of them.

## DRØMME
Når søvnen rammer min hjerne i nat  
Og dagen atter forsvinder  
Så har jeg mig i rummet efterladt  
Med dagens forbigående minder  

Blandt purpurgræs og zebrafisk  
Med arme istedet for fødder  
Vandrer jeg rundt i hjerneland  
Og alskinds væsener møder  

Minder formes til uigenkendelighed  
Når livets længsler mødes  
Hvor ingen behersker betænkelighed  
Når naturlovenes regler brydes  

Døde står op som var det igår  
I en rus af gensyns-endorfiner   
I søvnens disede efterår  
Hvor alle linjer rimer  

En ekskæreste kys så virkelighedsnær  
At puden væddes med tåre  
Et fabeldyr så majestætisk og sær  
En stormflod gennem mine åre  

En historie så medrivende fortalt  
At tidens tik forsvinder  
Hvordan jeg har opdigtet alt  
Er et svar jeg aldrig finder  

Når nattens forsvundne timer er talt  
Og dagen atter begynder  
Så har jeg mig i drømmen efterladt  
Med nattens forglemte hymner  

## TANKER

Ligeså hurtigt som den kom  
Ligeså hurtigt tog jeg med  
Et øjebliks uopmærksomhed, og jeg blev ført afsted  
På en rejse til en ufrivilig destination  
Til et sted, uden for tid, virkelighed, og uden dimension  

Én blev til to, blev til tre, og afsted  
Den ene første til den anden, og jeg fulgte bare med  
Hvorfor kom jeg derhen  
Hvad førte mig væk  
Vil du mig noget fortælle med utydeligt blæk?  

Et spindelvæv, et mylder - uden rationel facon  
Et systematisk kaos - med variende form  
Et plagende mantra fra noget dumt jeg fik sagt  
En pludselig åbenbart om hvor mine nøgler er lagt  

Sig mig nu sind, vil jeg kunne dig forstå  
Eller må jeg acceptere en viden jeg ikke kan få  
Et minde, en pige, eller en genial idé  
Hvad er mon det næste  
Jeg må vente og se  

## SAMMENSAT

Delta, epsilon, og komplekse tal  
Skrives op på formel  
Forudser jordens forfald  
Ord, komplimenter, og inderlighed  
Skrives op på formel  
Forklarer dig min kærlighed  
 
Atomer, ladninger, og universets støj  
Sættes i system  
Skaber kosmisk røg  
Magt, tvang, og uretfærdighed  
Sættes i system  
Styrer verdenens fred  
 
Farver, sprog, og religiøse hjem  
Deler mennesker op  
Skaber os og dem  
Perler, privilegier, og landegrænsens streg  
Deler verden op  
Skiller mig fra dig  

## PIGEN

Du er en pige af ben og kød  
Men alligevel ikke som de andre  
En forførende kraft fra dit længselsfulde skød  
Som forevigt vil mig forandre  

Begæret opfostre kærlighed  
Da jeg endelig giver mig til kende  
Et forandrede syn på alt hvad jeg ved  
Som en stum der genfinder sin stemme  

Som når solen står op over marker af dis  
Og tågen endelig letter  
Fik du optøet et hjerte af is  
Med hede og følsomme nætter  