---
title: "Getting Started Learning Target Trial Emulation"
description: "This post serves as a one-pager suggestion as to how one can get started learning about target trial emulation."
author: "Peter Bruun-Rasmussen"
date: "06/01/2025"
draft: False
date-modified: last-modified
bibliography: references.bib
categories: 
  - target trial emulation
  - causal inference
  - study design
  - targeted learning
---


## 1. Learn Causal Diagrams / Directed Acyclic Graphs (DAGs)

The core of target trial emulation (TTE) is the research question and to identify the study assumptions required to answer it. 
Here directed acyclic graphs (DAGs) are a key tool. This helps you identify confounding, and the adjustment sets required to obtain exchangeability (that is, emulate randomization). 

I suggest starting with the free course: [Causal Diagrams: Draw You Assumptions Before Your Conclusions](https://pll.harvard.edu/course/causal-diagrams-draw-your-assumptions-your-conclusions), by Miguel Hernan and Harvard.

## 2. Learn to use DAGitty 

Drawing DAGs and identifying open backdoor paths (confounding) and colliders can be challenging. Luckily, free tools exist that can help you do this automatically. 
One such tool is [DAGitty](https://www.dagitty.net/dags.html#).

There are several DAGitty tutorials on youtube, one suggestion could be this [one](https://www.youtube.com/watch?v=3euqrnD9w7c).

## 3. Read the “What if” Book

[Causal Inference: What if](https://miguelhernan.org/whatifbook) is written by Miguel Hernan and James Robins.
It is a somewhat long read, but I really encourage you to take up the challenge! 
This book is a must read if you want to master the art of target trial emulation. Read one chapter for breakfast each morning and you will soon be a TTE master. 
The book is freely available [here](https://miguelhernan.org/whatifbook).

## 4. Read PRINCIPLED 

The good people behind the RCT-DUPLICATE initiative have made a great guide on how to use healthcare registry data and claims data to generate decision grade evidence using TTE. This is great to have in hand when designing your next study. Their paper can be found here: [PRINCIPLED](https://www.bmj.com/content/384/bmj-2023-076460).

## 5. Trial Design 

**Active comparator new user design (ACNU) or sequential nested trial design?**

- If a clear time-zero exists for both the treatment and comparator arm - use the ACNU. The ACNU design will help you reduce bias from confounding by indication (@yoshida2015active).
- If no clear time-zero exists for one of the arms - use the sequential nested trial design (@hernan2008observational, @hernan2016specifying).

## 6. Learn the Statistical Methods Required 

I cannot state enough that the statistical methods should be your last focus point. These methods will not be able to help you obtain causal estimates if your TTE design is flawed.  
Commonly used in TTE and causal inference are the g-methods and preferably in combination via targeted learning. Don’t worry which of these methods to use, just use **targeted learning** - this is the most unbiased method for estimating your causal estimands. 

This stuff can feel overwhelming and complicated, but rest assured that you only need an intuitive understanding of how these methods work. Great implementations have already been made readily available in R for you to use. 

First get to understand inverse probability weighting and the g-formula. Then read about **targeted learning** and use that! 

- Introduction to [g-methods](https://pmc.ncbi.nlm.nih.gov/articles/PMC6074945/)
- Introduction to [targeted learning / TMLE](https://www.khstats.com/blog/tmle/tutorial)
- "Machine Learning in Causal Inference for Epidemiology": [Paper](https://link.springer.com/article/10.1007/s10654-024-01173-x)

**Software in R:**   
- [polle](https://cran.r-project.org/web/packages/polle/index.html) package  
- [lmtp](https://cran.r-project.org/web/packages/lmtp/index.html) package  
- [ltmle](https://cran.r-project.org/web/packages/ltmle/index.html) package

And please [don’t use](http://journals.lww.com/epidem/fulltext/2010/01000/the_hazards_of_hazard_ratios.4.aspx) the cox proportional hazards model! (@hernan2010hazards)

**Good luck!** - And feel free to reach out if you would like assistance, I would be happy to [collaborate](https://dk.linkedin.com/in/peter-bruun-rasmussen)!